### ISSUE TITLE
Command-line tools does not flag invalid teams for gen9vgc formats

### ISSUE THREAD

**Issue by Varan** [smogon/pokemon-showdown#10410]
Hi! 

When using the `validate-team` command, it does not catch invalid Pokémon teams for gen9vgc formats (`gen9vgc2024regd`, `gen9vgc2023series2`, `gen9vgc2023regulationebo3`, etc.) but it works correctly for all other formats (e.g. `gen7vgc2018`, `gen92v2doubles`, `gen8ou`, etc.).

As long as the pokemon, item, moves, nature, tera type, etc. exist, the team will not be flagged as invalid.
e.g. [this team](https://pokepast.es/d631b01e8a82f22b) has 4 Rillabooms with intimidate, geomancy, and 500 Atk EVs

I localhosted a server and the team was correctly flagged as invalid, so it seems like a issue with command-line tools in particular.

If anyone can point me in the right direction of how to try and fix this, or if there's something I might be doing wrong, please let me know!

**Comment by Karthik99999** [comment]
None of the formats you listed are valid. Regulation D is not a 2024 format (should be `gen9vgc2023regd`), and we no longer have reg e and reg b/series 2 in our formats file.

**Comment by Varan** [comment]
Ah gotcha, thanks for the clarification. Do you happen know of a way to programmatically validate teams for unlisted formats without manually creating custom rulesets for each format? (sorry, I'm new to this)

Also is there a reason why older formats like `gen7vgc2018` are kept but something like `gen9vgc2023regd` isn't?

**Comment by Karthik99999** [comment]
We do have `gen9vgc2023regd`. Ever since we started having rotating formats, we decided to only keep the format that was used at worlds for the specific year.

If you're getting teams from log files, then the `inputlog` in the file should have the commit the server was running on at the time, which you should be able to go back to get the format back. You could also just go back and get all of the vgc formats we have used and put them into the formats file so you don't have to keep changing where you are in the git history.

**Comment by Varan** [comment]
Sounds good I'll do just that, thanks so much for the help!
