### ISSUE TITLE
Battle Protocol: message after all updates are sent to the client

### ISSUE THREAD

**Issue by andrebastosdias** [smogon/pokemon-showdown#10543]
I believe others have experienced the same issue as I have, where you're unsure if all updates have been sent before taking action (unless I'm missing something). I understand the benefits of sending the request before the update messages, but isn't there an easier way to send a confirmation message once all updates have been sent?

**Comment by andrebastosdias** [comment]
@DaWoblefet said on stream that there is no interest in it because it would generate too many logs.

**Comment by DaWoblefet** [comment]
Confirming - since the client is able to process when the start of the next turn is without this, adding additional protocol to let the client know when the server is finished sending updates would cause a bunch of extra protocol sent that does nothing (which adds up over time). I'd recommend in your case to either modify your local server to send an ending message, or take a look at other python projects to see how they process knowing when a battle is complete.
