### ISSUE TITLE
Multi-battles and FFA

### ISSUE THREAD

**Issue by Zarel** [smogon/pokemon-showdown#2924]
I'm surprised there isn't already an issue tracking this.

Anyway, multi-battles and free-for-all (aka Battle Royale) battles should be implemented sooner rather than later.

I'll get on it eventually, but first I have some major refactors to how choices work on the client and server. Others should feel free to tackle this.

**Comment by acz13** [comment]
Well, if you don't want to change much there is always the hacky way to do it 😉 

Would probably be better to refactor the code though

**Comment by HoeenCoder** [comment]
A refactor would most likely be necessary to handle 4p battles, off the top of my head some of the things that would need to be handled are:

- Create a setup for 4p / modify the current setup for 2p.

- Handle 4 decisions, we could do this like doubles (possibly), but with each player controlling their own pokemon.

- Client battle screen would need changes to handle 4 players (sidebars showing teams and avatars).

- FFA rules would need to be added since the win conditions are different, Also to be handled is when a user runs out of pokemon but his/her partner still has some.

Thats just the tip of the iceburg though (probably, I need to research this more to get a more accurate look at the load). Has any work been done on multi-battles yet?

**Comment by adrifcastr** [comment]
so sadly it seems that nobody seems to be on it to do this / multi battle /friend list mode thingy.......

**Comment by HoeenCoder** [comment]
Ive been interested in trying some stuff out, but Im restricted atm so I cant do anything :(

**Comment by DeathlyPlays** [comment]
@Nineage iirc made progress on this but didn't get to the client part due to not being able to host one? Don't quote me on that

**Comment by tjjerome** [comment]
Is this still an active project?

**Comment by Zarel** [comment]
It's still planned. No current progress on it, though.

**Comment by MacChaeger** [comment]
For multibattles, what if we stored the two halves of the team in even/odd indices? Like, one player's half of the team is stored in 0, 2, and 4, and the other half is stored in 1, 3, and 5?

**Comment by Zarel** [comment]
Err, I was going to have the sides go even/odd, but I don't see a need to store the teams that way.

**Comment by MacChaeger** [comment]
I was thinking for multibattle to only actually have two sides.

**Comment by Zarel** [comment]
That sounds hacky. I think some things will need to be concentrated to the first two sides, but multiple sides shouldn't be that hard to implement.

**Comment by MacChaeger** [comment]
Yeah, the other idea I had would be to give sides a new `ally` property and change protocol from accessing `Side.pokemon` directly to `Side.getPokemon()` which would handle checking for an ally. Making `Side.pokemon` `private` should make it easy to enforce that.

**Comment by Zarel** [comment]
No, `side.pokemon` should not need to be private.

Are you thinking of `side.active`? That should probably be replaced with an accessor, yes.

**Comment by MacChaeger** [comment]
`side.active` would need a getter too, but there are places in the code that use `side.pokemon` where, in a multi-battle, the code would want to have pokemon from both allied sides, not just one half. In those cases, we'd need a getter anyway, so it makes sense to me to always use a single getter function with a parameter to determine whether or not you want the half or the whole.

**Comment by Zarel** [comment]
Which places are you thinking of?

The main examples I can think of accessing `side.pokemon` are Assist and Beat Up, which I'd assume don't apply to allied pokemon.

Also Whirlwind, which definitely can't switch in an allied pokemon.

**Comment by MacChaeger** [comment]
There's definitely some research I'd like done so we don't have to assume things.
Places that check `side.pokemon` directly (and aren't checking every side):

- Illusion - I **assume** this only checks one player's half.
- Aromatherapy/Heal Bell/Sparkly Swirl - I **assume** this cures both players' teams.
- Assist - I'm not going to guess either way on this one...
- Beat Up - ...or this one.
- Team Preview Mod - This is its own problem, but it should pair teams together.
- Sleep/Freeze Clause Mod - This is a policy thing, but I'd say they should apply to the full team.
- Mega evolution/Z-moves - From what I can find online, the limit is per-player, not per-team, but it doesn't hurt to be sure.
- Tie-breaking - I **assume** that the teams are considered as a whole in-game when breaking a tie. The current code would need modifying to handle that.
- Switching - Obviously restricted to per-player
- Swapping positions: not relevant because Ally Swap fails in multi battles.

I suppose there aren't as many as I originally assessed there to be, so it's probably fine to just make a function like `Side.fullTeam()` or something.
```
fullTeam() {
   return this.pokemon.concat(this.ally.pokemon);
}
```

**Comment by Zarel** [comment]
I would probably just want a `Pokemon#allies()` and `Pokemon#foes()` for active Pokémon.

For full teams, we can probably manually do the iteration. I do also want to support those free-for-all battles in I think XY?

**Comment by MacChaeger** [comment]
Free-for-all was introduced in Sun & Moon, and I'm avoiding those for now because I don't know how the client would handle having 4 totally separate teams.

**Comment by MacChaeger** [comment]
I think those would be best used as strictly for getting active Pokemon, and that we should still have a function for getting all a Pokemon's inactive allies across both players.

```
allies(adjacentOnly?: boolean): Pokemon[] {
   let allies = this.side.active;
   if (this.side.ally) allies.push(...this.side.ally.active);
   if (adjacentOnly) allies = allies.filter(ally => this.battle.isAdjacent(this, ally));
   return allies;
}

foes(adjacentOnly?: boolean): Pokemon[] {
   let foes = [];
   for (const side of this.battle.sides) {
      if (side !== this.side && side !== this.side.ally) foes.push(...side.active);
   }
   if (adjacentOnly) foes = foes.filter(foe => this.battle.isAdjacent(this, foe));
   return foes;
}
```
How are these?

**Comment by MacChaeger** [comment]
Do you plan on adding a `p3` and `p4` property to `Battle`s? Personally I think that if we're implementing 4 player battles, we should do away with those and just iterate through `Battle#sides`.

**Comment by MacChaeger** [comment]
Well, maybe keep them around for testing purposes, but I don’t think having the same block of code 4 times in a row makes sense.

**Comment by Zarel** [comment]
Yeah, I wouldn't add `p3` and `p4` properties.

**Comment by Zarel** [comment]
```js
   let allies = this.side.active;
   if (this.side.ally) allies.push(...this.side.ally.active);
```

...lol, spot the bug

**Comment by MacChaeger** [comment]
Perhaps I should open a draft pull request?

**Comment by MacChaeger** [comment]
I'm not sure what you're calling a bug, but the fact that `this.allies()` can return an array containing `this` is intentional. To my knowledge, there are no effects that target non-adjacent allies but not the user.

**Comment by Zarel** [comment]
The bug is that you're using `push` instead of `concat`, which means that your side's active list is now twice as long as it's supposed to be.

**Comment by Zarel** [comment]
I take my ally's Pokémon and add them to my own!

**Comment by Zarel** [comment]
before:

```
side.active = [Pikachu];
allySide.active = [Eevee];
```

after:

```
side.active = [Pikachu, Eevee];
allySide.active = [Eevee];
```

**Comment by MacChaeger** [comment]
OOOOOOH right, pointers.

**Comment by Spandamn** [comment]
https://github.com/Spandamn/Pokemon-Showdown/tree/multi6 Needs help
client: https://github.com/Spandamn/Pokemon-Showdown-Client/tree/multi1
challenging: `/challenge <opponent>,gen8multibattle@@@gen8ou,<teammate>`
accepting a challenge: `/acceptmulti <challenger, your teammate>`
Right now, challenge requests arent sent to teammates, they're just forced into battle.
Also, it has a invalid target bug which i do not know how to fix.

**Comment by Spandamn** [comment]
So insttead of challenging, now you can just lick for "search battle" and search for an ally from the ladder. when people people hop on the ladder, it matches you. https://github.com/Spandamn/Pokemon-Showdown/tree/multi7 
again, work needed, and only works with the client provided above!

**Comment by Ads20000** [comment]
[Gen 8] Multi Random Battle now available on challenging someone. Thanks so much Zarel(?) for implementing this!!! Am _hyped_!!!

**Comment by Zarel** [comment]
Oh, good reminder, this is finished.

The bulk of the work was done in #8152 and #7929.

There's a lot of work left regarding challenging and bringing teams in, but I don't think we need to track those in this issue.
