### ISSUE TITLE
Roomgame UI

### ISSUE THREAD

**Issue by Zarel** [smogon/pokemon-showdown#3759]
The Roomgame API was designed to centralize various features of games on PS, since the sim wasn't the only game people wanted to play.

I think the next step is to actually make a roomgame laid out like a battle.

The first step is actually really straightforward: You create a room for a game, and then you support just `|fieldhtml|` to set HTML inside the field, and `|controlshtml|` to set HTML for the controls.

![image](https://user-images.githubusercontent.com/551184/28007971-84dfd00a-6590-11e7-9d8a-d9269b76fc07.png)

So it'd be like this.

**Comment by panpawn** [comment]
How would ``|controlshtml|`` and ``|fieldhtml|`` be updated? Would it be like, ``|controlshtmlchange|`` and ``|fieldhtmlchange|``?

**Comment by Zarel** [comment]
It'd just be `|controlshtml|`. There's no reason why setting it and updating it can't be the same command.

**Comment by panpawn** [comment]
Agreed

**Comment by panpawn** [comment]
I started working on the client-end parts of this at https://github.com/Zarel/Pokemon-Showdown-Client/pull/968

**Comment by Zarel** [comment]
The important client parts are done in https://github.com/Zarel/Pokemon-Showdown-Client/commit/4591bad53e04b7696b42b89723e1a7b31437f53d

I'm going to leave this open; I want someone to write a roomgame using this, just so I can tell if it needs anything else.

**Comment by panpawn** [comment]
Note: The server-side parts for this still have to be done, if someone is looking for something to do

**Comment by Zarel** [comment]
I'm not sure if there are any server-side parts that need doing, besides literally "make a roomgame that uses it"?

**Comment by panpawn** [comment]
This would need server-side parts, yeah.  It can't be a chatroom - this entire premise is that this is a battle room.

When a battle room is created, the server uses:
```
Rooms.createBattle = function (roomid, format, p1, p2, options) {
	if (roomid && roomid.id) return roomid;
	if (!p1 || !p2) return false;
	if (!roomid) roomid = 'default';
	if (!Rooms.rooms.has(roomid)) {
		// console.log("NEW BATTLE ROOM: " + roomid);
		Monitor.countBattle(p1.latestIp, p1.name);
		Monitor.countBattle(p2.latestIp, p2.name);
		Rooms.rooms.set(roomid, new BattleRoom(roomid, format, p1, p2, options));
	}
	return Rooms(roomid);
};
```
(https://github.com/Zarel/Pokemon-Showdown/blob/master/rooms.js#L1442-L1453)
However, this doesn't really work for game rooms. Game rooms have more than one player, so specifying player1 and player2 is arbitrary to battle rooms, specifically.  Also, the format name.  Also, the monitor battle count (these aren't battles).

**Comment by Zarel** [comment]
Yeah, that should happen next.

**Comment by Morfent** [comment]
Would supporting subchannel protocol for room games,of all types be something worthwhile implementing? I think it'd be pretty handy to have for games that the current implementation of subchannels would be simple to reuse for, like Uno: subchannel 0 for non-players, 1 for the player whose turn is active, 2 for the rest of the players, and 3 for debug messages, for example. It could help move some of the work needed to send the appropriate messages to the appropriate users in the room for game updates over to the sockets workers instead of the main process, making them simpler to implement more efficiently

**Comment by Zarel** [comment]
Subchannels optimize sending different data to different players, at the cost of significantly less code readability.

I really don't think they're worth it here. You just have public data (to be added to roomlog) and private data (to be sent privately), as far as I'm aware.

**Comment by Morfent** [comment]
Another way they could be used is to allow users to be able to choose whether or not they want to spectate the game or ignore it entirely: subchannel 0 to ignore, 1 to spectate, 2 to play. Spectator messages aren't entirely public or private. Subchannels would make spectating a matter of moving users to a different subchannel rather than having to go through their previous names, comparing with players currently in the game, players kicked from the game, users blacklisted from playing the game, users already spectating, etc. Player messages wouldn't be entirely private in room games where users play on teams against each other, either. Subchannels wouldn't be useful for _all_ cases, but for those they would be useful to ha, they'd be much more legible to use than having to keep track of multiple lists of users in the room from the room game instance entirely manually

**Comment by Zarel** [comment]
...you can ignore a game entirely by leaving it. What would you be in a battle room for if you didn't want to watch the battle?

**Comment by Morfent** [comment]
Ok I think there's some kind of misunderstanding here. How would this UI be used for the chat plugins that already are room games?

**Comment by Zarel** [comment]
Does the UI look like a chatroom to you? o_O

The UI is clearly that of a battle room...

**Comment by Morfent** [comment]
Well obviously it doesn't look like a chatroom. I thought this was supposed to be a way of implementing more advanced game chat plugins that could be run in chatroom, but clearly I have no idea what this is aiming to be used for.

So what's the purpose of this?

**Comment by Zarel** [comment]
It was never my intention for games to be run directly in chatrooms. You should be making game rooms to run them in.

This system is intended to help support that, by supporting game rooms that look like battle rooms.

**Comment by Zarel** [comment]
I think this is mostly done at this point? Supposedly RPS even uses it successfully.

**Comment by Zarel** [comment]
Okay, I just tested out RPS and while it has a lot of room for improvement, none of it is related to the roomgame UI which seems very successful, so I'm closing this.

**Comment by Zarel** [comment]
Only took over three years after I made the API for it to be used though lol
