### ISSUE TITLE
Ditto should copy Morpeko's Aura wheel effects.

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6084]
What happens: When using the move transform or the ability imposter, ditto (or mew) does not copy the effects of Morpeko's Hangry Mode.

What should happen: As with most abilities, the user copying the ability should gain the effects of the ability, switching between modes in the case of Hangry mode,

Replays: [Transform + Morpeko ]( https://replay.pokemonshowdown.com/gen8customgame-1017296934)
[Original user report](https://www.smogon.com/forums/goto/post?id=8291290)

**Comment by Zarel** [comment]
You linked to the wrong original user report (your link is to Dauntless and Intrepid Sword).

I need research that shows that Ditto does copy mode-switching.

**Comment by KrisXV** [comment]
[6:26 PM] Anubis: Okay, what happens is this:
[6:26 PM] Anubis: 1) Ditto copies the form of Morpeko that is out and does not change forms after that.
[6:27 PM] Anubis: 2) Aura Wheel is electric type no matter what form was copied.

Ditto transformed into Morpeko does not switch formes so that works correctly.

the move typing remains electric but does end up being usable by Ditto while transformed, so that will need adjusted

**Comment by Lusamine** [comment]
Here are my videos showing what happens: https://imgur.com/a/XlWtiLD

**Comment by TZubiri** [comment]
Thank you for the research. So, with the exception of the electric typing bug that we don't have, the simulator mechanics cartridge cartridge correctly. I was not expecting this. I'll close the issue unless someone wants to implement the typing bug.

**Comment by KrisXV** [comment]
Showdown doesnt implement visual inferiorities regarding moves and instead opts to improve on them, such as showing Hidden Power display as its type CSS in battles
