### ISSUE TITLE
[Natdex OU] Ditto can copy a mega evolved Pokémon, and then Dynamax.

### ISSUE THREAD

**Issue by Shiny-andKittens** [smogon/pokemon-showdown#6141]
This is because the code suppresses the ability to Dynamax when holding certain items, but not when the Pokémon itself is Mega Evolved already.

(This could be important for Balanced Hackmons in the future)
![F00DC317-8FA9-45C3-8863-0B761D26CEE9](https://user-images.githubusercontent.com/19195628/70094971-88024680-161b-11ea-9c63-f1a11736814c.png)

**Comment by Zarel** [comment]
This is not a bug. Please don't report things that aren't bugs to our issue tracker. If you do this again, I'd have to ban you.

We have a perfectly serviceable bug report thread on Smogon, for people who are too lazy to understand bugs before reporting them: https://psim.us/bugs

**Comment by Zarel** [comment]
For the record, this is how it works in the games, too: Zacian and Zamazenta can't Dynamax, but a Ditto transformed into them can.

This has zero implications for Balanced Hackmons because mega evolution does not exist in Gen 8, and Dynamax does not exist in Gen 7.

For future reference, it's probably a good idea not report mechanics bugs in NatDex anywhere at all; just ask NatDex tier leaders whether or not the mechanic is intentional in the first place.
