### ISSUE TITLE
/learn issues

### ISSUE THREAD

**Issue by Lusamine** [smogon/pokemon-showdown#6281]
``/learn`` currently shows:
> In Gen 3, Shedinja can't learn Gust
> In Gen 3, Shedinja can't learn Silver Wind

Both of these are valid egg moves for Nincada and in Gen 3 (I believe also Gen 4), Shedinja should get all the moves of Ninjask at the level of evolving.  I've tested in-game to verify that Shedinja can indeed learn Silver Wind via egg breeding Nincada.

This moveset validates appropriately in teambuilder, and same if you replace Gust with Silver Wind:
> Shedinja @ Quick Claw  
> Ability: Wonder Guard  
> EVs: 252 Atk / 252 Spe  
> Adamant Nature  
> - Shadow Ball  
> - Gust  
> - Swords Dance

**Comment by Marty-D** [comment]
This appears to be because Shedinja has a different egg group from Nincada and Ninjask. Changing it to Bug gives more expected output from /learn:
```
In Gen 3, Shedinja can learn Silver Wind only when obtained from:
    Gen 3 egg: breed yanma, scizor, dustox, ninjask, ...
```
I only see fully evolved Pokemon in this list so that makes me think this issue is a minor regression from when @Zarel streamlined searching for valid egg move parents in the last validator refactor.

**Comment by Acquiescence3** [comment]
Hope this can be resolved.

**Comment by Lusamine** [comment]
Using this for other validator issues instead of creating more GitHub issues.

Using ``/learn`` on any GMax mon and old-gen moves will tell you to obtain it from an older generation.  Of course, this isn't possible unless we get some way to add GMax factor onto old-gen Pokemon.
![image](https://user-images.githubusercontent.com/30205550/82111077-e6be0700-9707-11ea-95c0-093074e44876.png)
