### ISSUE TITLE
single turn actions can carry into following turns

### ISSUE THREAD

**Issue by EvGym** [smogon/pokemon-showdown#6996]
if you bind a single-use action to a switch in effect (like say give an item the ability to cause the user to use protect upon switching in) and the user is brought in to replace a fainted pokemon, the protection effect continues to the next turn despite the pokemon being shown as coming in the previous turn.

This is probably due to the chat's turn display not being accurate with the actual turn being used in the code.

**Comment by Zarel** [comment]
Do you have an example replay?

**Comment by Zarel** [comment]
Oh, this is custom code? Please don't open issues for custom code in PS's repositories. The bug is arguably in your code, not ours.

We classify this sort of thing as "OM support" and while we're not _entirely_ opposed to making it easier to add your own items and abilities, I'd prefer not to have this sort of feature request cluttering the issue tracker; Suggestions is a better place for it: https://psim.us/suggestions

Since this is the second time you've done this, let me repeat myself as clearly as possible: do _NOT_ report problems with adding custom items/moves/etc to a PS repository. This is only for simulating Pokémon games and formats officially approved by Smogon.

**Comment by EvGym** [comment]
It really isn't a issue in my code at all. I even patches it. Here let me give you an example.

If i made a custom repository where i gave pikachu earthquake by sinply adding it to his learnset but whenever he used it he randomy dies who's code is bugged? Clearly in that case your code is bugged while my code exposed the issue. This case is exactly the same.

I will go ahead and add this issue there.

Arguably this is the first time i did this since both issues were posted almost simultaneously.

**Comment by Zarel** [comment]
> If i made a custom repository where i gave pikachu earthquake by sinply adding it to his learnset but whenever he used it he randomy dies who's code is bugged? Clearly in that case your code is bugged while my code exposed the issue. This case is exactly the same.

The reason we would consider this a bug is because adding moves to a learnset easily is a supported use-case. In other words, it's a feature we have decided to support, and if it doesn't work, that's a bug.

Items sending `|singleturn|` during the residual phase to mean "will last through to the end of the next turn" is _not_ a feature we have decided to support, because no Pokémon game does that, and no OM (custom Smogon format) has a use for it. If it doesn't work, that's a missing feature, not a bug.

To be fair, it's a useful feature to have, and if you were to PR a fix I would probably accept it. But it's just not the sort of thing I'd want an open issue for. We would fix it if the real Pokémon games ever had an item that worked that way, but otherwise we wouldn't consider it a bug.

> Arguably this is the first time i did this since both issues were posted almost simultaneously. Unless you are talking about the amulet coin thing?

You're right, I was more harsh than necessary and I'm sorry. I didn't notice that you posted this before I replied to the Tailwind report.

**Comment by EvGym** [comment]
As i word with the code i will see if i can find the souce of the problem. I imagine it could also be useful for fakemons if someone wanted to add an ability that did something similar.

If i fix the issue in my end i will make sure to set up a PR for it. I an still learning the code base though so it might be awhile.
