### ISSUE TITLE
"Uninvite" button doesn't work sometimes

### ISSUE THREAD

**Issue by Starmys** [smogon/pokemon-showdown#8361]
![image](https://user-images.githubusercontent.com/31166558/121392277-d1a2be80-c981-11eb-9432-4d359a23671b.png)

To reproduce the problem:
1. P1 challenges P2 a free-for-all / multi battle
2. P2 accepts the challenge
3. Invite P3
4. `/hideroom` or `/publicroom` before P3 accepts
5. Uninvite P3

And then we are in an embarrassing situation:
- P3 will be un-uninvitable
    - until someone public the room again, if the room is public at the beginning
    - forever, if the room is hidden at the beginning
- P3 cannot accept the invitation either

**Comment by Zarel** [comment]
Interesting. This should be fixable.

**Comment by nojaa3** [comment]
This bug has a second way to trigger the outcome in above screenshot. Which is says submitted.
The first three steps are same.
1. P1 challenges P2 a free-for-all battle
2. P2 accepts the challenge
3. Invite P3
4.  P3 logs out or rejects challenge
5.  It is stuck at similar state, which the text says that player submitted, while P3 actually logged out or rejected challenge.

This bug also prevents inviting anybody else as the submitted text stays even after person rejected or logged-out. I tested this way in FFAs only, because we were trying to arrange a FFA battle.

**Comment by Zarel** [comment]
Figured it out, changing battle privacy renames the room, which is interfering with the invite.
