### ISSUE TITLE
Projects with low Build Activity - Survey

### ISSUE THREAD

**Issue by jadsonjs** [smogon/pokemon-showdown#8586]
Dear Developers of project **smogon/pokemon-showdown**,

We are conducting a study on CI metrics and we noticed that in your project, something peculiar happened.

During the period you are using Travis CI, the project passed by a long period of inactivity.
We noticed that the TravisCI configuration file (.travis.yml) was committed to your project on the date of **2014-08-17**.
But there is only a build history in TravisCI for a very short period, between **2018-04-18** and **2018-05-09**, in which were performed suddenly **217** builds.

Please, we would like you to answer this short survey with just 4 questions to help us identify the cause of this behavior.

https://forms.gle/UkkFrxpi7MNscYmV7

**Comment by Zarel** [comment]
Unfortunately, this happened too long ago for me to answer the survey questions. All I can tell you is that we switched from Travis CI to GitHub Actions because Travis CI was getting worse and worse. Understandable because we were an open-source project they weren't making money from, but since GitHub Actions is free, I don't see how we could possibly be worth it for Travis CI to continue supporting.
