### ISSUE TITLE
Requiring acceptance or rejection of Open Teamsheet before allowing Timer

### ISSUE THREAD

**Issue by Gazoney** [smogon/pokemon-showdown#9308]
Would we be able to get a change in the order of operations for VGC matches that prevents the timer from starting until an answer to the Open Teamsheet prompt has been given?
In open teamsheet matches, I don't want to decide on the 4 that I'm bringing to the match until I've looked through the options that my opponent has. Often in matches, a player either doesn't respond for a minute or so until they put on the timer and other matches the players have the timer start automatically, which means I'm burning through my time waiting for them to accept the prompt.

Ideally what I'm asking for is that a player can't turn that timer on (or it gets put on hold if automatic) until they've chosen to either accept or reject the teamsheet offer. Not only would this prevent players from losing "Your Time" while waiting for the opponent to respond, but saves people time so that they no longer sit there until the opponent makes their decision if they want to play with the Open Teamsheet.

**Comment by DaWoblefet** [comment]
Your Time for Team Preview doesn't count towards Your Time given for the rest of the match.

What you're suggesting would allow players to stall indefinitely at Team Preview. You could just start a game, never respond to the OTS prompt, and the match would never proceed because you can't turn on timer. This would really suck on low ladder especially if someone is just afk.

Maybe you mean that the individual player shouldn't be able to turn on timer until OTS is accepted/rejected, rather than both players. But that doesn't really seem to solve the problem you're after - players can still opt not to respond to either option, which will implicitly reject OTS, but you wouldn't know until their Team Preview Your Time ran out.

At the end of the day, short of assigning players losses if they don't choose to accept/deny OTS before Team Preview timer expires, the current opt-in approach is the best we've got without creating a second ladder ([which we're not going with at this time for other reasons](https://twitter.com/DaWoblefet/status/1612662954679275520)). From reports I've seen, it seems the majority of players on ladder prefer CTS for one reason or another, and forcing an explicit confirmation with threat of a loss seems too harsh.
