### ISSUE TITLE
Interaction of Pressure with PP and Leppa Berry

### ISSUE THREAD

**Issue by dodopool** [smogon/pokemon-showdown#9627]
Hello PS! Developers

Replay: https://replay.pokemonshowdown.com/gen9customgame-1895520297

Consider the replay above, in which:

1. Muk has a Leppa Berry and OHKO's Tandemaus with drain punch. Now, Muk has 15/16 PPs of drain punch left. 
2. Eternatus comes in and has the ability Pressure. Due to this, 2 PPs will be deducted for each drain punch used by Muk
3. In the following turns, Muk uses drain punch. 
4. When Muk has 1 PP left and it uses drain punch, PS! sets the PP of drain punch as **-1/16** temporarily 
5. Because Muk has Leppa Berry, the PP becomes, as per PS! as -1 + 10 = 9 (most likely from the code @ https://github.com/smogon/pokemon-showdown/blob/317d3cd79b621dc9a3d85723822193504bb47335/data/mods/partnersincrime/items.ts#L8)
6. However, Leppa berry should've restored the PP to 10 points. I think if the PP would've been set to 0 instead of -1, then the bug wouldn't have occurred. 

I found this bug to be in Gen 7 and Gen 8 too. Can you please check this!

Thanks

**Comment by DaWoblefet** [comment]
dodopool,

This is a client-side issue (the display) not a server-side issue (the actual amount of PP restored to Muk is correctly 10). The code snippet you linked is not relevant as it relates to Partners in Crime, which was not in the Custom Game format you used as an example. From Muk's perspective:
![image](https://github.com/smogon/pokemon-showdown/assets/23667022/6136d73a-677d-48b1-8d76-64359fbe2a54)

Right now, we support negative PP numbers because side servers may change PP information on their attacks. You can see a discussion of this problem on [Smogon ](https://www.smogon.com/forums/threads/pp-shows-as-1-due-to-facing-pressure-pokemon.3717565/)and on [Showdown's client repository](https://github.com/smogon/pokemon-showdown-client/pull/1741).
